# Generated by Django 3.2.6 on 2022-01-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0006_alter_gameroom_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(related_name='played_in', to='multiplayer_chess.Player'),
        ),
    ]
