# Generated by Django 3.2.6 on 2022-02-28 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0007_alter_gameroom_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
