# Generated by Django 4.2 on 2023-05-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0011_alter_game_player1_alter_game_player2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='turn',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.CharField(default='Placeholder', max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.CharField(default='Placeholder', max_length=30),
        ),
    ]
