# Generated by Django 4.2 on 2023-05-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0014_alter_game_player1_alter_game_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('classic', 'Classic'), ('atomic', 'Atomic')], max_length=10, null=True),
        ),
    ]
