# Generated by Django 4.2 on 2023-05-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0015_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fen',
            field=models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', null=True),
        ),
    ]
