# Generated by Django 4.2 on 2023-05-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0016_game_fen'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.CharField(choices=[('w', 'white'), ('b', 'black')], default='w', max_length=1),
        ),
    ]
