# Generated by Django 4.2 on 2023-05-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0019_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('classic', 'Classic'), ('atomic', 'Atomic'), ('antichess', 'Antichess'), ('suicide', 'Suicide')], max_length=10, null=True),
        ),
    ]
