# Generated by Django 4.2 on 2023-05-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0021_alter_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='elo',
            field=models.JSONField(default='{"classic": 1000, "atomic": 1000, "antichess": 1000}'),
        ),
    ]
