# Generated by Django 4.2 on 2023-05-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0024_remove_game_elo_antichess_remove_game_elo_atomic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='elo_partita',
            field=models.IntegerField(null=True),
        ),
    ]
