# Generated by Django 4.2 on 2023-05-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0034_chesstournament_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chesstournament',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='chesstournament',
            name='start_date',
        ),
        migrations.AddField(
            model_name='chesstournament',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='chesstournament',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chesstournament',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='tournament', to='multiplayer_chess.game'),
        ),
        migrations.AlterField(
            model_name='chesstournament',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='multiplayer_chess.profile'),
        ),
        migrations.AlterField(
            model_name='chesstournament',
            name='status',
            field=models.CharField(choices=[('iscrizione', 'Iscrizioni'), ('ottavi', 'Ottavi'), ('quarti', 'Quarti'), ('semifinale', 'Semifinale'), ('finale', 'Finale')], max_length=11, null=True),
        ),
    ]
