# Generated by Django 4.2 on 2023-05-27 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multiplayer_chess', '0036_game_numero_torneo_alter_chesstournament_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='elo_partita',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='numero_torneo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vincitore', to=settings.AUTH_USER_MODEL),
        ),
    ]
