# Generated by Django 4.2 on 2023-05-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0037_alter_game_elo_partita_alter_game_numero_torneo_and_more'),
        ('multiplayer_chess', '0037_alter_game_winner'),
    ]

    operations = [
    ]
