# Generated by Django 4.2 on 2023-04-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('player1', models.CharField(default=None, max_length=30)),
                ('player2', models.CharField(default=None, max_length=30)),
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
