# Generated by Django 4.2 on 2023-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.CharField(default='Placeholder', max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.CharField(default='Placeholder', max_length=30),
        ),
    ]
