# Generated by Django 3.2.6 on 2022-01-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0002_alter_player_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_ingame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
