# Generated by Django 3.2.6 on 2022-01-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0003_auto_20220111_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='multiplayer_chess.player'),
        ),
    ]
