# Generated by Django 4.2 on 2023-05-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0018_game_status_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('created', "Partita creata, in attesa dell'avversario"), ('started', 'Partita iniziata'), ('finished', 'Partita terminata')], default='created', max_length=10),
        ),
    ]
