# Generated by Django 4.2 on 2023-05-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0020_alter_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('classic', 'Classic'), ('atomic', 'Atomic'), ('antichess', 'Antichess'), ('kingofthehill', 'Kingofthehill'), ('threecheck', 'Threecheck'), ('horde', 'Horde'), ('racingkings', 'Racingkings')], max_length=13, null=True),
        ),
    ]
