# Generated by Django 4.2 on 2023-05-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0025_game_elo_partita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('players', models.ManyToManyField(related_name='tournaments', to='multiplayer_chess.profile')),
            ],
        ),
    ]
