# Generated by Django 4.2 on 2023-05-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0028_chesstournament_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesstournament',
            name='tier',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('esperto', 'Esperto')], max_length=13, null=True),
        ),
    ]
