# Generated by Django 4.2 on 2023-05-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0029_alter_chesstournament_tier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-data_partita']},
        ),
        migrations.AddField(
            model_name='game',
            name='data_partita',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
