# Generated by Django 4.2 on 2023-05-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0030_alter_game_options_game_data_partita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chesstournament',
            name='tier',
        ),
        migrations.AddField(
            model_name='chesstournament',
            name='elo_max',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chesstournament',
            name='elo_min',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chesstournament',
            name='matches',
            field=models.ManyToManyField(related_name='tournament', to='multiplayer_chess.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='bracket_position',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
    ]
