# Generated by Django 4.2.1 on 2023-05-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0032_remove_chesstournament_elo_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesstournament',
            name='matches',
            field=models.ManyToManyField(related_name='tournament', to='multiplayer_chess.game'),
        ),
    ]
