# Generated by Django 4.2.1 on 2023-05-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0033_chesstournament_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesstournament',
            name='status',
            field=models.CharField(choices=[('ottavi', 'Ottavi'), ('quarti', 'Quarti'), ('semifinale', 'Semifinale'), ('finale', 'Finale')], max_length=11, null=True),
        ),
    ]
