# Generated by Django 4.2 on 2023-05-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer_chess', '0035_remove_chesstournament_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='numero_torneo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chesstournament',
            name='status',
            field=models.CharField(choices=[('iscrizione', 'Iscrizioni'), ('ottavi', 'Ottavi'), ('quarti', 'Quarti'), ('semifinale', 'Semifinale'), ('finale', 'Finale'), ('terminato', 'Terminato')], max_length=11, null=True),
        ),
    ]
